### ISSUE TITLE
When an advert is playing

### ISSUE THREAD

**Issue by Fasani** [nadavbar/node-spotify-webhelper#1]
When an advert is playing this fails..

res.track.length

Do you know what the res object looks like when an advert is playing, sorry to ask but it will save me some time not waiting for an advert...

**Comment by nadavbar** [comment]
Not sure how it looks, but why not just check if the res.track/ res.track.length object is defined and skip if it's not?

**Comment by Fasani** [comment]
Cheers dude, This is what I did... it also fixes another issue when a track is not available in the users country.

It will be in my V2 release coming this week.
