### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by ConcernedHobbit** [nadavbar/node-spotify-webhelper#6]
See http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process for fix

**Comment by nadavbar** [comment]
Can you please provide a stack trace? Or more details regarding your scenario?
The use of child_process in the code ignores stdout, so I suspect this might come from one of the modules dependencies. I can't verify this until I'll have a trace.

If you integrated this fix into the code and it solved the issue, please feel free to send a pull request.

**Comment by wsmigielski** [comment]
Having the same problem
{ err:
   { Error: stdout maxBuffer exceeded
       at Socket.<anonymous> (child_process.js:264:14)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at Pipe.onread (net.js:551:20) cmd: 'wmic process list /format:csv' },
  msg: 'unable to enumerate processes' }

**Comment by wsmigielski** [comment]
Found the solution!
An old version of wintools is used. 
Just download an up to date version or edit the code yourself 
https://github.com/anodejs/node-wintools/commit/624c3cbf94e8dda35b03bd048f21f59b2b43258f
